name = "star-point-quiz-time"
compatibility_date = "2024-01-01"
pages_build_output_dir = "dist"

[env.production.vars]
VITE_SUPABASE_URL = "https://ssxlmdopzqtdxjqqpxrj.supabase.co"
VITE_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNzeGxtZG9wenF0ZHhqcXFweHJqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI1MzkyNTMsImV4cCI6MjA2ODExNTI1M30.YMJxEXXdOX_0AIV9AFeGitZoRlv2kcvcy4KehMtC4T8"